SELECT CITY, CHAR_LENGTH(CITY)
FROM STATION
WHERE CHAR_LENGTH(CITY) = (SELECT MIN(CHAR_LENGTH(CITY))
                          FROM STATION)
ORDER BY CITY
LIMIT 1;

SELECT CITY, CHAR_LENGTH(CITY)
FROM STATION
WHERE CHAR_LENGTH(CITY) = (SELECT MAX(CHAR_LENGTH(CITY))
                          FROM STATION)
ORDER BY CITY
LIMIT 1;
