SELECT DISTINCT(H.HISTORY_ID), 
    (CASE
        WHEN (DATEDIFF(H.END_DATE, H.START_DATE)+1) BETWEEN 0 AND 6
        THEN TRUNCATE((DATEDIFF(H.END_DATE, H.START_DATE)+1) * C.DAILY_FEE, 0)
        WHEN (DATEDIFF(H.END_DATE, H.START_DATE)+1) BETWEEN 7 AND 29
        THEN TRUNCATE((DATEDIFF(H.END_DATE, H.START_DATE)+1) * C.DAILY_FEE * 95/100, 0)
        WHEN (DATEDIFF(H.END_DATE, H.START_DATE)+1) BETWEEN 30 AND 89
        THEN TRUNCATE((DATEDIFF(H.END_DATE, H.START_DATE)+1) * C.DAILY_FEE * 92/100, 0)
        WHEN (DATEDIFF(H.END_DATE, H.START_DATE)+1) >= 90
        THEN TRUNCATE((DATEDIFF(H.END_DATE, H.START_DATE)+1) * C.DAILY_FEE * 85/100, 0) END) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC
