SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, U.GENDER, COUNT(DISTINCT(U.USER_ID)) AS USERS
FROM USER_INFO U
INNER JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, U.GENDER
ORDER BY YEAR ASC, MONTH ASC, U.GENDER ASC;



# 주문의 수가 아니라 년/월/성별에 맞게 주문한 회원의 수이므로 COUNT(DISTINCT(U.USER_ID))를 사용하여 중복되는 열을 제거한다
