SELECT DISTINCT AA.CAR_ID, 
CASE WHEN BB.CAR_ID IS NOT NULL THEN '대여중' ELSE '대여 가능'
END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AA
LEFT JOIN (SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE) BB
ON AA.CAR_ID = BB.CAR_ID
ORDER BY CAR_ID DESC;

/*
2024/02/17 수정
날짜 데이터도 MAX() 같은 집계 함수가 적용이 된다!
아래 코드가 훨씬 간단한 것 같다
*/

SELECT CAR_ID, 
    CASE
        WHEN MAX('2022-10-16' BETWEEN START_DATE AND END_DATE) 
        THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC
