SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
INNER JOIN HR_GRADE G
ON E.EMP_NO = G.EMP_NO
WHERE G.EMP_NO = (SELECT EMP_NO
                 FROM HR_GRADE
                 GROUP BY EMP_NO
                 ORDER BY SUM(SCORE) DESC
                 LIMIT 1)
GROUP BY G.EMP_NO
