SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC;

/*
HAVING 절이 있었지...
*/
SELECT USER_ID, PRODUCT_ID
FROM (SELECT USER_ID, PRODUCT_ID, COUNT(*) AS cnt
     FROM ONLINE_SALE
     GROUP BY USER_ID, PRODUCT_ID) AS os
WHERE cnt >= 2
ORDER BY USER_ID ASC, PRODUCT_ID DESC
