SELECT DISTINCT(H.HISTORY_ID), 
    (CASE
        WHEN (DATEDIFF(H.END_DATE, H.START_DATE)+1) BETWEEN 0 AND 6
        THEN TRUNCATE((DATEDIFF(H.END_DATE, H.START_DATE)+1) * C.DAILY_FEE, 0)
        WHEN (DATEDIFF(H.END_DATE, H.START_DATE)+1) BETWEEN 7 AND 29
        THEN TRUNCATE((DATEDIFF(H.END_DATE, H.START_DATE)+1) * C.DAILY_FEE * 95/100, 0)
        WHEN (DATEDIFF(H.END_DATE, H.START_DATE)+1) BETWEEN 30 AND 89
        THEN TRUNCATE((DATEDIFF(H.END_DATE, H.START_DATE)+1) * C.DAILY_FEE * 92/100, 0)
        WHEN (DATEDIFF(H.END_DATE, H.START_DATE)+1) >= 90
        THEN TRUNCATE((DATEDIFF(H.END_DATE, H.START_DATE)+1) * C.DAILY_FEE * 85/100, 0) END) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC

/*
위에 코드는 내가 일일이 테이블을 들여다보고 하드 코딩한거라 다른 문제에는 써먹지를 못한다.
아래 코드는 LEFT JOIN과 FROM절에 새로운 컬럼을 추가하는 형태로 문제를 풀었다.
*/
SELECT H.HISTORY_ID,
        CASE
            WHEN P.DISCOUNT_RATE IS NULL THEN DAILY_FEE * RENT_DATE
            ELSE ROUND(DAILY_FEE * ((100 - P.DISCOUNT_RATE) / 100) * RENT_DATE, 0)
        END AS FEE
FROM (SELECT HISTORY_ID, CAR_ID,
     DATEDIFF(END_DATE, START_DATE) + 1 AS RENT_DATE,
     CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 7 AND 29 THEN '7일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 30 AND 89 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
     END AS DURATION_TYPE
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS H
LEFT JOIN CAR_RENTAL_COMPANY_CAR AS C
ON H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON C.CAR_TYPE = P.CAR_TYPE AND H.DURATION_TYPE = P.DURATION_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC
